### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by LukasW94** [edawson/gfakluge#18]
https://github.com/edawson/gfakluge/blob/ba4e7a77f72e5dc47de429782418762fc42e47fe/src/gfakluge.hpp#L420-L424

This code is giving me the following build error:

> 
> Code/gfakluge/src/gfakluge.hpp:420:52: error: ‘Date’ does not name a type
> ostream& operator<<(ostream& os, const Date& dt)
> Code/gfakluge/src/gfakluge.hpp:420:60: error: ‘std::ostream& gfak::GFAKluge::operator<<(std::ostream&, const int&)’ must take exactly one argument
> ostream& operator<<(ostream& os, const Date& dt)

Am I doing something wrong? 
I'm using gcc version 6.3.0 20170519 (Ubuntu/Linaro 6.3.0-18ubuntu2~16.04)

**Comment by edawson** [comment]
Nope, it was a copy/paste error on my end. Should now be fixed.

**Comment by edawson** [comment]
Hey @LukasW94 , is this fixed? I've gone ahead and closed but reopen it if you're still having issues.
