### ISSUE TITLE
path_elem orientations are backward in GFA 0.1

### ISSUE THREAD

**Issue by adamnovak** [edawson/gfakluge#34]
It looks like path entry orientations are true for forward, and false for backward:

https://github.com/edawson/gfakluge/blob/1a78943536f36e0d08b4d2944ee4f0066fe610a8/src/gfakluge.hpp#L102

But when loading GFA files like this:

```
H	VN:Z:0.1
S	1	CAAATAAG
S	2	A
S	3	G
P	1	x	1	+	8M
P	3	x	2	+	1M
L	1	+	2	+	0M
L	1	+	3	+	0M
```

I get path_elem objects that look like this:

```
P	x	1-,3-	8M,1M
```

In other words, the `orientations` flags are backward when reading GFA 0.1 paths.

**Comment by adamnovak** [comment]
@edawson Could you have a look at this, please? I'm wanting to use this fix in a PR to vg, and to use it it has to be merged in here.

**Comment by edawson** [comment]
This looks good. It has always been confusing that the walk_elem that Erik drew up used true for is_reversed and the path_elem of GFA1+ used essentially the opposite. I think you fix is fine - I'm merging.
