### ISSUE TITLE
Update submodules

### ISSUE THREAD

**Issue by cartoonist** [edawson/gfakluge#60]
There are some fixes recently for tinyFA and pliib libraries which are direct or transitive dependencies of GFAKluge. It would be great if you could update their corresponding submodules. I have already submitted a PR (edawson/tinyFA#2) for updating pliib submodule in tinyFA. But after that the tinyFA should be updated for GFAKluge too.

**Comment by edawson** [comment]
I think I've got them fully up to date now in #61 (including your PR in tinyFA). Thanks for the help!

**Comment by edawson** [comment]
Closing this, but please reopen if needed!
